### ISSUE TITLE
[Bug] API problem

### ISSUE THREAD

**Issue by nfkgu6630** [whats2000/CodeBRT#17]
Hi, I just downloaded it and found that my api key doesn't work. In fact, I did entered the api key of openai and clicked the "Close and Save", but it wasn't inputed in the configuration panel because every time I close it and open it again, the key just disappeared.
![image](https://github.com/user-attachments/assets/c41efcc0-0a7b-4008-b8e5-ada61deb9e99)

**Comment by whats2000** [comment]
Thanks for report. I think the issue is related to the key storage. Try login by click account icon at left bottom > Login to sync settings. The key is store as cross device which require login to use currently. I might find a better way to store it soon, before that try restart VSCode after login to your account for a quick fix.

**Comment by whats2000** [comment]
Please tell me if it still happen after login and restart which can help me debug!

**Comment by nfkgu6630** [comment]
Actually, I had already logged in VSCode at that time. Also, I just tried to re-login and restart VSCode, but it still doesn't work.

**Comment by nfkgu6630** [comment]
Although it is inputed in the settings, the same error still pops up.

**Comment by whats2000** [comment]
Ok, I think there is an issue in the config system. Try click settings gear icon (At bottom left in VSCode) > extension > find the API key input box for direct modify settings. Can you also report your device and VSCode version (At top bar `about`)? So I can try reproduce.

**Comment by nfkgu6630** [comment]
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by whats2000** [comment]
Ok, after I tested. I found the issue! The issue is relative to the fact that no current workspace was found. Try opening a workspace to let the history in. I will fix it in a recent update soon.

To open a folder you can follow the steps below:
1. Click File at the top bar
2. Click `open folder`
3. Either select the project you want to work on or create a new folder for chat history storage.

I will ensure that the settings are able to save without a workspace in the next update.
Status: [Check the issue board](https://github.com/users/whats2000/projects/2/views/3?sliceBy%5Bvalue%5D=whats2000)
Thank you for helping me to improve!

**Comment by whats2000** [comment]
Here is a patch, I will release it at the new 0.4.5 version

Commit: https://github.com/whats2000/CodeBRT/commit/c1db3018aa78c4af2e3ac60f9348752a0a60ec44
